apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: yscrmetachatbot001.azurecr.io/example-app:20240916.5
          env:
            - name: IMAGE_VERSION
              value: 20240916.5
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ys-cred
---
apiVersion: v1
kind: Service
metadata:
  name: example-app-service
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
